import fs from "fs-extra";
import { v4 as uuidv4 } from "uuid";
import { getGroqClient, groqConfig } from "../config/groq.js";

function safeJsonParse(text) {
  try {
    return JSON.parse(text);
  } catch {
    const match = text.match(/\{[\s\S]*\}/);

    if (match) {
      return JSON.parse(match[0]);
    }

    throw new Error("Groq response was not valid JSON");
  }
}

function slugify(text) {
  return String(text || "generated-test")
    .toLowerCase()
    .replace(/https?:\/\//g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 60);
}

function reduceTestCasesForAI(testCaseData) {
  if (!testCaseData || !Array.isArray(testCaseData.testSuites)) {
    return [];
  }

  return testCaseData.testSuites.map((suite) => ({
    featureName: suite.featureName || "",
    featureType: suite.featureType || "",
    priority: suite.priority || "",
    testCases: Array.isArray(suite.testCases)
      ? suite.testCases.slice(0, 6).map((testCase) => ({
          testCaseId: testCase.testCaseId || "",
          title: testCase.title || "",
          type: testCase.type || "",
          priority: testCase.priority || "",
          steps: testCase.steps || [],
          expectedResult: testCase.expectedResult || "",
          automationFeasibility: testCase.automationFeasibility || ""
        }))
      : []
  }));
}

export async function generatePlaywrightScripts({ websiteUrl, testCaseData }) {
  await fs.ensureDir("tests/generated");

  const groq = getGroqClient();
  const reducedTestSuites = reduceTestCasesForAI(testCaseData);

  const prompt = `
You are ASEA, an Autonomous Software Engineering Agent.

Generate Playwright test scripts from structured QA test cases.

Website URL:
${websiteUrl}

QA Test Case Data:
${JSON.stringify(
    {
      websiteUrl: testCaseData.websiteUrl,
      pageTitle: testCaseData.pageTitle,
      totalFeatures: testCaseData.totalFeatures,
      totalTestCases: testCaseData.totalTestCases,
      testSuites: reducedTestSuites
    },
    null,
    2
  )}

Return ONLY valid JSON.

IMPORTANT:
Do NOT return code inside one multi-line string.
Return code as an array of strings using "contentLines".
Each line of code must be one string in the array.

Use this exact JSON structure:

{
  "files": [
    {
      "fileName": "login-tests.spec.js",
      "description": "Playwright tests for login page",
      "contentLines": [
        "import { test, expect } from '@playwright/test';",
        "",
        "test('page loads successfully', async ({ page }) => {",
        "  await page.goto('${websiteUrl}');",
        "  await expect(page).toHaveURL('${websiteUrl}');",
        "});"
      ]
    }
  ]
}

Rules:
- Use JavaScript, not TypeScript.
- Use @playwright/test.
- Every test must start with await page.goto("${websiteUrl}");
- Use string URLs with toHaveURL, not regex URLs.
- Correct: await expect(page).toHaveURL("${websiteUrl}");
- Wrong: await expect(page).toHaveURL(/https://example.com/);
- Prefer stable selectors:
  - page.getByRole()
  - page.getByText()
  - page.getByLabel()
  - page.getByPlaceholder()
  - page.locator()
- Do not include markdown.
- Do not include explanations.
- Do not include triple backticks.
- Do not use fake selectors if uncertain.
- If selectors are uncertain, generate safe page-load and visibility tests.
`;

  const response = await groq.chat.completions.create({
    model: groqConfig.model,
    messages: [
      {
        role: "user",
        content: prompt
      }
    ],
    temperature: groqConfig.temperature
  });

  const content = response.choices[0].message.content;
  const parsed = safeJsonParse(content);

  const files = Array.isArray(parsed.files) ? parsed.files : [];

  if (files.length === 0) {
    throw new Error("No Playwright test files generated by AI.");
  }

  const savedFiles = [];

  for (const file of files) {
    const safeName = slugify(file.fileName || testCaseData.pageTitle || websiteUrl);
    const filePath = `tests/generated/${safeName}-${uuidv4()}.spec.js`;

    const fileContent = buildFileContent(file, websiteUrl);

    await fs.writeFile(filePath, fileContent);

    savedFiles.push({
      fileName: file.fileName || `${safeName}.spec.js`,
      description: file.description || "Generated Playwright test file",
      filePath
    });
  }

  return {
    totalFiles: savedFiles.length,
    files: savedFiles,
    generatedAt: new Date().toISOString()
  };
}

function buildFileContent(file, websiteUrl) {
  let finalContent = "";

  if (Array.isArray(file.contentLines)) {
    finalContent = file.contentLines.join("\n");
  } else if (typeof file.content === "string") {
    finalContent = file.content;
  }

  finalContent = String(finalContent || "").trim();

  finalContent = finalContent
    .replace(/^```js/g, "")
    .replace(/^```javascript/g, "")
    .replace(/^```/g, "")
    .replace(/```$/g, "")
    .trim();

  if (!finalContent.includes("@playwright/test")) {
    finalContent = `import { test, expect } from "@playwright/test";\n\n${finalContent}`;
  }

  if (!finalContent.includes("test(")) {
    finalContent = `
import { test, expect } from "@playwright/test";

test("page loads successfully", async ({ page }) => {
  await page.goto("${websiteUrl}");
  await expect(page).toHaveURL("${websiteUrl}");
});
`;
  }

  finalContent = finalContent.replace(
    /await\s+expect\(page\)\.toHaveURL\(\/https?:\/\/[^;]+\/\);/g,
    `await expect(page).toHaveURL("${websiteUrl}");`
  );

  return finalContent;
}